export const playlistJson = [
    {
      name: "Daily Mix 1",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705484403/fo8dmqrfuzsgtf5thn8l.jpg",
      description: "",
    },
    {
      name: "Daily Mix 2",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705485058/cd6ofgiv6fljsfnadwmz.jpg",
      description: "",
    },
    {
      name: "Daily Mix 3",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705485146/zlsole7ycakt8zwbynr2.jpg",
      description: "The unseen, subhumans and crass",
    },
    {
      name: "Daily Mix 4",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705485291/u3px1wohafl6add8vxop.jpg",
      description: "Slipknot Gojira and more...",
    },
    {
      name: "Daily Mix 5",
      imgUrl:
        "https://dailymix-images.scdn.co/v2/img/ab6761610000e5ebafa254b2a224584485286526/5/en-GB/default",
      description: "Slipknot Gojira and more...",
    },
    {
      name: "Daily Mix 6",
      imgUrl:
        "https://res.cloudinary.com/dpnevk8db/image/upload/v1709397808/asset_87_lj78fs.jpg",
      description: "Slipknot Gojira and more...",
    },
    {
      name: "Daily Mix 7",
      imgUrl:
        "https://res.cloudinary.com/dpnevk8db/image/upload/v1709397807/asset_86_z1fqnt.jpg",
      description: "Slipknot Gojira and more...",
    },
    {
      name: "Countdown to Extinction",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705485455/krxxylpmikv6vvnm4l61.jpg",
      description: "Megadeth",
    },
    {
      name: "Metal Mix",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705485738/gg0qam4qfxqwcodwki6q.jpg",
      description: "Popular Metal bands",
    },
    {
      name: "Discover Weekly",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705350332/fxslryvz4zqsx7pfkcpj.jpg",
      description: "Rock out while you game",
    },
    {
      name: "Rock Radio",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705503633/knuquvidkzfouyydavku.jpg",
      description: "Best Rock radio",
    },
    {
      name: "Best songs from the 90s",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705503723/lvybhjwjyfbrogktlub9.jpg",
      description: "Best decade for music",
    },
    {
      name: "Ultimate music",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705503730/lhtkyfm4u73gwuylecxs.jpg",
      description: "",
    },
    {
      name: "Rock Me Up",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705503755/gm8ebgg5regraquiftw2.jpg",
      description: "",
    },
    {
      name: "Liked Songs",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1705451341/ebpe6nnlgajtmfyldt4a.png",
      description: "",
    },
    {
      name: "Chill Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397810/asset_88_z3fdr9.jpg",
      description: "Relax and unwind",
    },
    {
      name: "Workout Beats",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397812/asset_89_sdfvbh.jpg",
      description: "Get pumped up",
    },
    {
      name: "Top Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397813/asset_90_afdzbh.jpg",
      description: "Today's biggest hits",
    },
    {
      name: "Classic Rock",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397815/asset_91_fghndy.jpg",
      description: "Rock legends",
    },
    {
      name: "Jazz Essentials",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397817/asset_92_gbvnsy.jpg",
      description: "Smooth and relaxing",
    },
    {
      name: "Hip Hop Bangers",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397818/asset_93_gvbnbh.jpg",
      description: "Hot beats and rhymes",
    },
    {
      name: "Indie Favorites",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397820/asset_94_gbvnmg.jpg",
      description: "Indie gems",
    },
    {
      name: "Country Roads",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397822/asset_95_hgbvmh.jpg",
      description: "Country hits",
    },
    {
      name: "Pop Party",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397823/asset_96_vfgbnh.jpg",
      description: "Party anthems",
    },
    {
      name: "Reggae Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397825/asset_97_vgbmhg.jpg",
      description: "Feel the rhythm",
    },
    {
      name: "Classical Favorites",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397827/asset_98_gbvnhy.jpg",
      description: "Timeless classics",
    },
    {
      name: "Electronic Beats",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397829/asset_99_gvnmbh.jpg",
      description: "Electronic hits",
    },
    {
      name: "Blues Legends",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397830/asset_100_vgbmhy.jpg",
      description: "Blues greats",
    },
    {
      name: "Soulful Sounds",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397832/asset_101_gbvnmy.jpg",
      description: "Soul classics",
    },
    {
      name: "Folk Favorites",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397834/asset_102_vgbnfy.jpg",
      description: "Folk tunes",
    },
    {
      name: "Punk Rock",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397835/asset_103_vgbnby.jpg",
      description: "Punk anthems",
    },
    {
      name: "Latin Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397837/asset_104_vgbnsy.jpg",
      description: "Latin rhythms",
    },
    {
      name: "Dance Party",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397839/asset_105_vgbnry.jpg",
      description: "Dancefloor fillers",
    },
    {
      name: "R&B Essentials",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397840/asset_106_vgbnqy.jpg",
      description: "Smooth R&B",
    },
    {
      name: "Alternative Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397842/asset_107_vgbnvb.jpg",
      description: "Alternative favorites",
    },
    {
      name: "Acoustic Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397844/asset_108_vgbnxv.jpg",
      description: "Stripped-down tunes",
    },
    {
      name: "Epic Soundtracks",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397845/asset_109_vgbnrb.jpg",
      description: "Movie scores",
    },
    {
      name: "Party Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397847/asset_110_vgbnmb.jpg",
      description: "All-time party hits",
    },
    {
      name: "Summer Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397849/asset_111_vgbnvy.jpg",
      description: "Sunny tunes",
    },
    {
      name: "Road Trip",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397850/asset_112_vgbnxy.jpg",
      description: "Music for the road",
    },
    {
      name: "Morning Boost",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397852/asset_113_vgbnny.jpg",
      description: "Start your day right",
    },
    {
      name: "Chill Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397854/asset_114_vgbnbv.jpg",
      description: "Relaxing hits",
    },
    {
      name: "Throwback Jams",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397856/asset_115_vgbnqv.jpg",
      description: "Nostalgic tunes",
    },
    {
      name: "Festival Anthems",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397857/asset_116_vgbnrv.jpg",
      description: "Festival favorites",
    },
    {
      name: "Happy Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397859/asset_117_vgbnwv.jpg",
      description: "Feel-good music",
    },
    {
      name: "Relax & Unwind",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397860/asset_118_vgbntv.jpg",
      description: "Calm and relaxing",
    },
    {
      name: "Focus",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397862/asset_119_vgbnrh.jpg",
      description: "Music for concentration",
    },
    {
      name: "Sleep Sounds",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397864/asset_120_vgbnph.jpg",
      description: "Relaxing sounds for sleep",
    },
    {
      name: "Cooking Music",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397865/asset_121_vgbngh.jpg",
      description: "Tunes for the kitchen",
    },
    {
      name: "Gaming",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397867/asset_122_vgbnjh.jpg",
      description: "Music for gaming",
    },
    {
      name: "Workout Motivation",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397869/asset_123_vgbnkh.jpg",
      description: "Get motivated",
    },
    {
      name: "Sunday Chill",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397870/asset_124_vgbnbh.jpg",
      description: "Relaxing Sunday tunes",
    },
    {
      name: "Feel Good Friday",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397872/asset_125_vgbnfh.jpg",
      description: "Start your weekend right",
    },
    {
      name: "Party Starter",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397874/asset_126_vgbndh.jpg",
      description: "Get the party started",
    },
    {
      name: "Road Trip Classics",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397876/asset_127_vgbnlh.jpg",
      description: "Classic road trip songs",
    },
    {
      name: "Evening Chill",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397877/asset_128_vgbnfh.jpg",
      description: "Wind down in the evening",
    },
    {
      name: "Morning Coffee",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397879/asset_129_vgbnhh.jpg",
      description: "Start your day with coffee",
    },
    {
      name: "Travel Tunes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397881/asset_130_vgbnjh.jpg",
      description: "Music for your travels",
    },
    {
      name: "Weekend Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397882/asset_131_vgbnbh.jpg",
      description: "Weekend playlist",
    },
    {
      name: "Relaxation Station",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397884/asset_132_vgbnwh.jpg",
      description: "Ultimate relaxation",
    },
    {
      name: "Driving Beats",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397886/asset_133_vgbnlh.jpg",
      description: "Music for driving",
    },
    {
      name: "Feel Good",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397887/asset_134_vgbnph.jpg",
      description: "Uplifting tunes",
    },
    {
      name: "Dance Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397889/asset_135_vgbnjh.jpg",
      description: "Hit the dance floor",
    },
    {
      name: "Workout",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397891/asset_136_vgbngh.jpg",
      description: "Pump up your workout",
    },
    {
      name: "Study Beats",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397892/asset_137_vgbnsh.jpg",
      description: "Focus on your studies",
    },
    {
      name: "Nature Sounds",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397894/asset_138_vgbntf.jpg",
      description: "Relax with nature",
    },
    {
      name: "Indie Pop",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397896/asset_139_vgbntv.jpg",
      description: "Best indie pop hits",
    },
    {
      name: "Lounge",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397897/asset_140_vgbndv.jpg",
      description: "Chill lounge music",
    },
    {
      name: "Yoga",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397899/asset_141_vgbnsv.jpg",
      description: "Music for yoga",
    },
    {
      name: "Happy Tunes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397901/asset_142_vgbnfh.jpg",
      description: "Feel happy",
    },
    {
      name: "Sleep Tight",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397903/asset_143_vgbnnh.jpg",
      description: "Music for a good night's sleep",
    },
    {
      name: "Motivation",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397904/asset_144_vgbnph.jpg",
      description: "Get motivated",
    },
    {
      name: "Romantic Hits",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397906/asset_145_vgbnqh.jpg",
      description: "Songs for romance",
    },
    {
      name: "Mellow Vibes",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397908/asset_146_vgbnwh.jpg",
      description: "Chill out music",
    },
    {
      name: "Workout Anthems",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397910/asset_147_vgbnyh.jpg",
      description: "Get energized",
    },
    {
      name: "Calm",
      imgUrl:
        "http://res.cloudinary.com/dpnevk8db/image/upload/v1709397911/asset_148_vgbnyv.jpg",
      description: "Relaxing tunes",
    },
  ];
  
  export const usersJson = [
    {
      username: "Demo-user-one",
      password: "Demo-user-one",
      email: "a@a",
      avatarUrl:
        "https://res.cloudinary.com/dpnevk8db/image/upload/v1719231948/avatar4_wmaocu.jpg",
    },
    {
      username: "Demo-user-two",
      password: "Demo-user-two",
      email: "b@b",
      avatarUrl:
        "https://res.cloudinary.com/dpnevk8db/image/upload/v1719231948/avatar5_zvr4cg.jpg",
    },
    {
      username: "Demo-user-three",
      password: "Demo-user-three",
      email: "c@c",
      avatarUrl:
        " https://res.cloudinary.com/dpnevk8db/image/upload/v1719136220/avatar1_izzwlj.jpg",
    },
  ];
  
 export const songsJson = [
    {
      name: "Sheena Is A Punk Rocker (Official Music Video)",
      artist: "Ramones",
      type: "song",
      duration: "02:56",
      youtubeId: "yCW7Aw8ugOI",
      thumbnail: "https://i.ytimg.com/vi/yCW7Aw8ugOI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705347571892",
    },
    {
      name: "Ever Fallen In Love (With Someone You Shouldn’t’ve?) (TOTP, 1978)",
      artist: "Buzzcocks",
      type: "song",
      duration: "02:35",
      youtubeId: "0Af7ayYIJ9w",
      thumbnail: "https://i.ytimg.com/vi/0Af7ayYIJ9w/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705347594247",
    },
    {
      name: "What Do I Get? (Official Video)",
      artist: "Buzzcocks",
      type: "song",
      duration: "02:55",
      youtubeId: "iMXR7w76VZU",
      thumbnail: "https://i.ytimg.com/vi/iMXR7w76VZU/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705347608183",
    },
    {
      name: "הכוכבים דולקים על אש קטנה 1990",
      artist: "משינה",
      type: "song",
      duration: "03:27",
      youtubeId: "FilQhY2Pjq0",
      thumbnail: "https://i.ytimg.com/vi/FilQhY2Pjq0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705415525385",
    },
  
    {
      name: "Girl&#39;s Not Grey (Official Music Video)",
      artist: "AFI",
      type: "song",
      duration: "03:13",
      youtubeId: "1Yzu-4kJg6g",
      thumbnail: "https://i.ytimg.com/vi/1Yzu-4kJg6g/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705484876401",
    },
    {
      name: "All I Want (Official Music Video)",
      artist: "The Offspring",
      type: "song",
      duration: "01:56",
      youtubeId: "us8OhI-OTHg",
      thumbnail: "https://i.ytimg.com/vi/us8OhI-OTHg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705484899719",
    },
    {
      name: "Hunger Strike",
      artist: "Temple Of The Dog",
      type: "song",
      duration: "04:04",
      youtubeId: "VUb450Alpps",
      thumbnail: "https://i.ytimg.com/vi/VUb450Alpps/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485075254",
    },
    {
      name: "Be Yourself",
      artist: "Chris Cornnell",
      type: "song",
      duration: "03:33",
      youtubeId: "BITljGb9Wdk",
      thumbnail: "https://i.ytimg.com/vi/BITljGb9Wdk/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485094053",
    },
    {
      name: "Alive (Official Video)",
      artist: "Pearl Jam",
      type: "song",
      duration: "04:56",
      youtubeId: "qM0zINtulhM",
      thumbnail: "https://i.ytimg.com/vi/qM0zINtulhM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485108632",
    },
    {
      name: "Scream Out",
      artist: "The Unseen",
      type: "song",
      duration: "03:05",
      youtubeId: "dzVe8IgpbSc",
      thumbnail: "https://i.ytimg.com/vi/dzVe8IgpbSc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485159249",
    },
    {
      name: "Do They Owe Us a Living?",
      artist: "The Unseen",
      type: "song",
      duration: "01:25",
      youtubeId: "o2tyOGGO32M",
      thumbnail: "https://i.ytimg.com/vi/o2tyOGGO32M/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485179920",
    },
    {
      name: "All Gone Dead",
      artist: "The Unseen",
      type: "song",
      duration: "01:54",
      youtubeId: "wVFELYoXS2Y",
      thumbnail: "https://i.ytimg.com/vi/wVFELYoXS2Y/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485198535",
    },
    {
      name: "Sphinx [OFFICIAL VIDEO]",
      artist: "Gojira",
      type: "song",
      duration: "04:03",
      youtubeId: "kl-2GUMijPM",
      thumbnail: "https://i.ytimg.com/vi/kl-2GUMijPM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485372026",
    },
    {
      name: "Psychosocial [OFFICIAL VIDEO] [HD]",
      artist: "Slipknot",
      type: "song",
      duration: "05:03",
      youtubeId: "5abamRO41fE",
      thumbnail: "https://i.ytimg.com/vi/5abamRO41fE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485385226",
    },
    {
      name: "Square Hammer (Official Music Video)",
      artist: "Ghost",
      type: "song",
      duration: "04:00",
      youtubeId: "VqoyKzgkqR4",
      thumbnail: "https://i.ytimg.com/vi/VqoyKzgkqR4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485400224",
    },
    {
      name: "Countdown To Extinction (Remastered/2012)",
      artist: "Megadeath",
      type: "song",
      duration: "04:18",
      youtubeId: "3jejVarHf1U",
      thumbnail: "https://i.ytimg.com/vi/3jejVarHf1U/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485529748",
    },
    {
      name: "Symphony Of Destruction",
      artist: "Megadeath",
      type: "song",
      duration: "04:07",
      youtubeId: "WdoXZf-FZyA",
      thumbnail: "https://i.ytimg.com/vi/WdoXZf-FZyA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485563649",
    },
    {
      name: "Legends Never Die (Official Video) | Napalm Records",
      artist: "THE DARK SIDE OF THE MOON",
      type: "song",
      duration: "04:32",
      youtubeId: "sSSUfiD47_I",
      thumbnail: "https://i.ytimg.com/vi/sSSUfiD47_I/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485614577",
    },
    {
      name: "Vortex (Official Video) | Napalm Records",
      artist: "JINJER",
      type: "song",
      duration: "04:03",
      youtubeId: "AiaOSGZTwtY",
      thumbnail: "https://i.ytimg.com/vi/AiaOSGZTwtY/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485634782",
    },
    {
      name: "Nemesis (OFFICIAL VIDEO)",
      artist: "ARCH ENEMY",
      type: "song",
      duration: "04:28",
      youtubeId: "n9AcG0glVu4",
      thumbnail: "https://i.ytimg.com/vi/n9AcG0glVu4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705485646582",
    },
    {
      name: "עד מחר",
      artist: "אביתר בנאי",
      type: "song",
      duration: "04:28",
      youtubeId: "g_gFnDyi2Ho",
      thumbnail: "https://i.ytimg.com/vi/g_gFnDyi2Ho/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705503586415",
    },
    {
      name: "לך אלי (אודיו)",
      artist: "מאיר בנאי",
      type: "song",
      duration: "05:49",
      youtubeId: "6VpzTnosBjA",
      thumbnail: "https://i.ytimg.com/vi/6VpzTnosBjA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705503606748",
    },
    {
      name: "הלהיטים הגדולים ברצף",
      artist: "אהוד בנאי",
      type: "song",
      duration: "02:24:34",
      youtubeId: "Jn08I-kkcPw",
      thumbnail: "https://i.ytimg.com/vi/Jn08I-kkcPw/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705503620256",
    },
    {
      name: "LataMaolata",
      artist: "Ada",
      type: "song",
      duration: "03:21",
      youtubeId: "wbofhcDT_UE",
      thumbnail: "https://i.ytimg.com/vi/wbofhcDT_UE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705529079487",
    },
    {
      name: "New",
      artist: "TyeTribbett",
      type: "song",
      duration: "03:16",
      youtubeId: "WDlTm3XiGn8",
      thumbnail: "https://i.ytimg.com/vi/WDlTm3XiGn8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705531368955",
    },
    {
      name: "Yellow Submarine",
      artist: "TheBeatles",
      type: "song",
      duration: "02:46",
      youtubeId: "m2uTFF_3MaA",
      thumbnail: "https://i.ytimg.com/vi/m2uTFF_3MaA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549329",
    },
    {
      name: "HeyJude",
      artist: "TheBeatles",
      type: "song",
      duration: "08:10",
      youtubeId: "A_MjCqQoLLA",
      thumbnail: "https://i.ytimg.com/vi/A_MjCqQoLLA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549326",
    },
    {
      name: "Dont Let MeDown",
      artist: "The Beatles",
      type: "song",
      duration: "03:32",
      youtubeId: "NCtzkaL2t_Y",
      thumbnail: "https://i.ytimg.com/vi/NCtzkaL2t_Y/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549322",
    },
  
    {
      name: "Now And Then",
      artist: "The Beatles",
      type: "song",
      duration: "04:36",
      youtubeId: "Opxhh9Oh3rg",
      thumbnail: "https://i.ytimg.com/vi/Opxhh9Oh3rg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549309",
    },
    {
      name: "Billie Jean",
      artist: "Michael Jackson",
      type: "song",
      duration: "04:56",
      youtubeId: "Zi_XLOBDo_Y",
      thumbnail: "https://i.ytimg.com/vi/Zi_XLOBDo_Y/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549972",
    },
    {
      name: "Smooth Criminal",
      artist: "Michael Jackson",
      type: "song",
      duration: "09:26",
      youtubeId: "h_D3VFfhvs4",
      thumbnail: "https://i.ytimg.com/vi/h_D3VFfhvs4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549975",
    },
    {
      name: "They Dont Care",
      artist: "Michael Jackson",
      type: "song",
      duration: "04:42",
      youtubeId: "QNJL6nfu__Q",
      thumbnail: "https://i.ytimg.com/vi/QNJL6nfu__Q/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549976",
    },
    {
      name: "Beat It",
      artist: "Michael Jackson",
      type: "song",
      duration: "04:59",
      youtubeId: "oRdxUFDoQe0",
      thumbnail: "https://i.ytimg.com/vi/oRdxUFDoQe0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549979",
    },
    {
      name: "Earth Song",
      artist: "Michael Jackson",
      type: "song",
      duration: "06:45",
      youtubeId: "XAi3VTSdTxU",
      thumbnail: "https://i.ytimg.com/vi/XAi3VTSdTxU/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787549981",
    },
    {
      name: "Cant Help Falling In Love",
      artist: "Elvis Presley",
      type: "song",
      duration: "03:01",
      youtubeId: "vGJTaP6anOU",
      thumbnail: "https://i.ytimg.com/vi/vGJTaP6anOU/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550345",
    },
    {
      name: "Jail houseRock",
      artist: "Elvis Presley",
      type: "song",
      duration: "02:44",
      youtubeId: "gj0Rz-uP4Mk",
      thumbnail: "https://i.ytimg.com/vi/gj0Rz-uP4Mk/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550347",
    },
    {
      name: "My Way",
      artist: "Elvis Presley",
      type: "song",
      duration: "03:47",
      youtubeId: "ixbcvKCl4Jc",
      thumbnail: "https://i.ytimg.com/vi/ixbcvKCl4Jc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550349",
    },
    {
      name: "Suspicious minds",
      artist: "Elvis Presley",
      type: "song",
      duration: "04:34",
      youtubeId: "RxOBOhRECoo",
      thumbnail: "https://i.ytimg.com/vi/RxOBOhRECoo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550351",
    },
    {
      name: "If I Can Dream",
      artist: "Elvis Presley",
      type: "song",
      duration: "03:13",
      youtubeId: "u-pP_dCenJA",
      thumbnail: "https://i.ytimg.com/vi/u-pP_dCenJA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550352",
    },
    {
      name: "La Is la Bonita",
      artist: "Madonna",
      type: "song",
      duration: "04:01",
      youtubeId: "zpzdgmqIHOQ",
      thumbnail: "https://i.ytimg.com/vi/zpzdgmqIHOQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550847",
    },
    {
      name: "Hung Up",
      artist: "Madonna",
      type: "song",
      duration: "05:34",
      youtubeId: "EDwb9jOVRtU",
      thumbnail: "https://i.ytimg.com/vi/EDwb9jOVRtU/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550849",
    },
    {
      name: "Like AP rayer",
      artist: "Madonna",
      type: "song",
      duration: "05:38",
      youtubeId: "79fzeNUqQbQ",
      thumbnail: "https://i.ytimg.com/vi/79fzeNUqQbQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550850",
    },
    {
      name: "Frozen",
      artist: "Madonna",
      type: "song",
      duration: "05:29",
      youtubeId: "XS088Opj9o0",
      thumbnail: "https://i.ytimg.com/vi/XS088Opj9o0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550852",
    },
    {
      name: "Material Girl",
      artist: "Madonna",
      type: "song",
      duration: "04:46",
      youtubeId: "6p-lDYPR2P8",
      thumbnail: "https://i.ytimg.com/vi/6p-lDYPR2P8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787550854",
    },
    {
      name: "Angry",
      artist: "The Rolling Stones",
      type: "song",
      duration: "03:46",
      youtubeId: "_mEC54eTuGw",
      thumbnail: "https://i.ytimg.com/vi/_mEC54eTuGw/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551323",
    },
    {
      name: "Paint It Black",
      artist: "The Rolling Stones",
      type: "song",
      duration: "03:47",
      youtubeId: "O4irXQhgMqg",
      thumbnail: "https://i.ytimg.com/vi/O4irXQhgMqg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551329",
    },
    {
      name: "Sympathy For The Devil",
      artist: "The Rolling Stones",
      type: "song",
      duration: "08:49",
      youtubeId: "Jwtyn-L-2gQ",
      thumbnail: "https://i.ytimg.com/vi/Jwtyn-L-2gQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551337",
    },
    {
      name: "YouCantAlway...",
      artist: "TheRollingSt...",
      type: "song",
      duration: "04:29",
      youtubeId: "Ef9QnZVpVd8",
      thumbnail: "https://i.ytimg.com/vi/Ef9QnZVpVd8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551346",
    },
    {
      name: "Satisfaction",
      artist: "TheRollingSt...",
      type: "song",
      duration: "03:55",
      youtubeId: "nrIPxlFzDi0",
      thumbnail: "https://i.ytimg.com/vi/nrIPxlFzDi0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551355",
    },
    {
      name: "BestSongsofB...",
      artist: "BobDylanGrea...",
      type: "song",
      duration: "01:18:51",
      youtubeId: "kHjzuqq3b44",
      thumbnail: "https://i.ytimg.com/vi/kHjzuqq3b44/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551892",
    },
    {
      name: "Blowin39inth...",
      artist: "BobDylan",
      type: "song",
      duration: "02:51",
      youtubeId: "MMFj8uDubsE",
      thumbnail: "https://i.ytimg.com/vi/MMFj8uDubsE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551897",
    },
    {
      name: "Hurricane",
      artist: "BobDylan",
      type: "song",
      duration: "08:35",
      youtubeId: "bpZvg_FjL3Q",
      thumbnail: "https://i.ytimg.com/vi/bpZvg_FjL3Q/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551906",
    },
    {
      name: "TambourineMa...",
      artist: "Mr",
      type: "song",
      duration: "05:56",
      youtubeId: "OeP4FFr88SQ",
      thumbnail: "https://i.ytimg.com/vi/OeP4FFr88SQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551911",
    },
    {
      name: "obDylanGreat...",
      artist: "B",
      type: "song",
      duration: "01:00:25",
      youtubeId: "PIjru91ycm0",
      thumbnail: "https://i.ytimg.com/vi/PIjru91ycm0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787551917",
    },
    {
      name: "BestSongsofE...",
      artist: "EltonJohnGre...",
      type: "song",
      duration: "01:58:19",
      youtubeId: "polqRNmPJRE",
      thumbnail: "https://i.ytimg.com/vi/polqRNmPJRE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552390",
    },
    {
      name: "Sacrifice",
      artist: "EltonJohn",
      type: "song",
      duration: "04:42",
      youtubeId: "NrLkTZrPZA4",
      thumbnail: "https://i.ytimg.com/vi/NrLkTZrPZA4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552392",
    },
    {
      name: "I39mStillSta...",
      artist: "EltonJohn",
      type: "song",
      duration: "03:03",
      youtubeId: "ZHwVBirqD2s",
      thumbnail: "https://i.ytimg.com/vi/ZHwVBirqD2s/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552394",
    },
    {
      name: "YourSong",
      artist: "EltonJohn",
      type: "song",
      duration: "03:49",
      youtubeId: "GlPlfCy1urI",
      thumbnail: "https://i.ytimg.com/vi/GlPlfCy1urI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552398",
    },
    {
      name: "RocketMan",
      artist: "EltonJohn",
      type: "song",
      duration: "04:43",
      youtubeId: "DtVBCG6ThDk",
      thumbnail: "https://i.ytimg.com/vi/DtVBCG6ThDk/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552399",
    },
    {
      name: "WholeLottaLo...",
      artist: "LedZeppelin",
      type: "song",
      duration: "04:49",
      youtubeId: "HQmmM_qwG4k",
      thumbnail: "https://i.ytimg.com/vi/HQmmM_qwG4k/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552742",
    },
    {
      name: "MothershipLe...",
      artist: "LedZeppelin",
      type: "song",
      duration: "02:15:15",
      youtubeId: "FDMq9ie0ih0",
      thumbnail: "https://i.ytimg.com/vi/FDMq9ie0ih0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552744",
    },
    {
      name: "StairwayToHe...",
      artist: "LedZeppelin",
      type: "song",
      duration: "08:03",
      youtubeId: "QkF3oxziUI4",
      thumbnail: "https://i.ytimg.com/vi/QkF3oxziUI4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552747",
    },
    {
      name: "StairwayToHe...",
      artist: "LedZeppelin",
      type: "song",
      duration: "10:49",
      youtubeId: "Ly6ZhQVnVow",
      thumbnail: "https://i.ytimg.com/vi/Ly6ZhQVnVow/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552749",
    },
    {
      name: "BlackDog",
      artist: "LedZeppelin",
      type: "song",
      duration: "05:30",
      youtubeId: "6tlSx0jkuLM",
      thumbnail: "https://i.ytimg.com/vi/6tlSx0jkuLM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787552751",
    },
    {
      name: "TheDarkSideO...",
      artist: "PinkFloyd",
      type: "song",
      duration: "42:56",
      youtubeId: "k9ynZnEBtvw",
      thumbnail: "https://i.ytimg.com/vi/k9ynZnEBtvw/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553138",
    },
    {
      name: "WishYouWereH...",
      artist: "PinkFloyd",
      type: "song",
      duration: "06:09",
      youtubeId: "84Tq-eAJIk4",
      thumbnail: "https://i.ytimg.com/vi/84Tq-eAJIk4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553141",
    },
    {
      name: "Comfortablyn...",
      artist: "PinkFloyd",
      type: "song",
      duration: "06:55",
      youtubeId: "_FrOQC-zEog",
      thumbnail: "https://i.ytimg.com/vi/_FrOQC-zEog/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553143",
    },
    {
      name: "WishYouWereH...",
      artist: "PinkFloyd",
      type: "song",
      duration: "04:54",
      youtubeId: "IXdNnw99-Ic",
      thumbnail: "https://i.ytimg.com/vi/IXdNnw99-Ic/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553144",
    },
    {
      name: "HighHopes",
      artist: "PinkFloyd",
      type: "song",
      duration: "07:49",
      youtubeId: "7jMlFXouPk8",
      thumbnail: "https://i.ytimg.com/vi/7jMlFXouPk8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553146",
    },
    {
      name: "SpaceOddity",
      artist: "DavidBowie",
      type: "song",
      duration: "05:05",
      youtubeId: "iYYRH4apXDo",
      thumbnail: "https://i.ytimg.com/vi/iYYRH4apXDo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553500",
    },
    {
      name: "DavidBowieBe...",
      artist: "DavidBowieGr...",
      type: "song",
      duration: "01:43:59",
      youtubeId: "pyzwYRqn3nA",
      thumbnail: "https://i.ytimg.com/vi/pyzwYRqn3nA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553501",
    },
    {
      name: "LifeOnMars",
      artist: "DavidBowie",
      type: "song",
      duration: "04:10",
      youtubeId: "AZKcl4-tcuo",
      thumbnail: "https://i.ytimg.com/vi/AZKcl4-tcuo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553503",
    },
    {
      name: "Heroes",
      artist: "DavidBowie",
      type: "song",
      duration: "07:33",
      youtubeId: "bsYp9q3QNaQ",
      thumbnail: "https://i.ytimg.com/vi/bsYp9q3QNaQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553504",
    },
    {
      name: "Let39sDance",
      artist: "DavidBowie",
      type: "song",
      duration: "04:09",
      youtubeId: "VbD_kBJc_gI",
      thumbnail: "https://i.ytimg.com/vi/VbD_kBJc_gI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553506",
    },
    {
      name: "BohemianRhap...",
      artist: "Queen",
      type: "song",
      duration: "06:00",
      youtubeId: "fJ9rUzIMcZQ",
      thumbnail: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553822",
    },
    {
      name: "Don39tStopMe...",
      artist: "Queen",
      type: "song",
      duration: "03:33",
      youtubeId: "HgzGwKwLmgM",
      thumbnail: "https://i.ytimg.com/vi/HgzGwKwLmgM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553823",
    },
    {
      name: "QueenGreates...",
      artist: "TheBestOfQue...",
      type: "song",
      duration: "03:29:35",
      youtubeId: "HYuHNX7hBzQ",
      thumbnail: "https://i.ytimg.com/vi/HYuHNX7hBzQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553825",
    },
    {
      name: "GreatestHits",
      artist: "Queen",
      type: "song",
      duration: "01:19:21",
      youtubeId: "j440-D5JhjI",
      thumbnail: "https://i.ytimg.com/vi/j440-D5JhjI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553826",
    },
    {
      name: "TheShowMustG...",
      artist: "Queen",
      type: "song",
      duration: "04:23",
      youtubeId: "t99KH0TR-J4",
      thumbnail: "https://i.ytimg.com/vi/t99KH0TR-J4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787553828",
    },
    {
      name: "Won39tGetFoo...",
      artist: "TheWho",
      type: "song",
      duration: "09:10",
      youtubeId: "UDfAdHBtK_Q",
      thumbnail: "https://i.ytimg.com/vi/UDfAdHBtK_Q/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554169",
    },
    {
      name: "WhoAreYou",
      artist: "TheWho",
      type: "song",
      duration: "05:13",
      youtubeId: "PNbBDrceCy8",
      thumbnail: "https://i.ytimg.com/vi/PNbBDrceCy8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554170",
    },
    {
      name: "BabaO39riley",
      artist: "TheWho",
      type: "song",
      duration: "05:07",
      youtubeId: "x2KRpRMSu4g",
      thumbnail: "https://i.ytimg.com/vi/x2KRpRMSu4g/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554171",
    },
    {
      name: "BabaO39Riley",
      artist: "TheWho",
      type: "song",
      duration: "05:20",
      youtubeId: "Gu9HhYv0C7E",
      thumbnail: "https://i.ytimg.com/vi/Gu9HhYv0C7E/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554173",
    },
    {
      name: "PinballWizar...",
      artist: "TheWho",
      type: "song",
      duration: "02:51",
      youtubeId: "-J03yCE15rg",
      thumbnail: "https://i.ytimg.com/vi/-J03yCE15rg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554175",
    },
    {
      name: "WithOrWithou...",
      artist: "U2",
      type: "song",
      duration: "04:53",
      youtubeId: "ujNeHIo7oTE",
      thumbnail: "https://i.ytimg.com/vi/ujNeHIo7oTE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554669",
    },
    {
      name: "One",
      artist: "U2",
      type: "song",
      duration: "04:34",
      youtubeId: "ftjEcrrf7r0",
      thumbnail: "https://i.ytimg.com/vi/ftjEcrrf7r0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554671",
    },
    {
      name: "WithOrWithou...",
      artist: "U2",
      type: "song",
      duration: "05:00",
      youtubeId: "6DeDzsCGbsQ",
      thumbnail: "https://i.ytimg.com/vi/6DeDzsCGbsQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554672",
    },
    {
      name: "BeautifulDay",
      artist: "U2",
      type: "song",
      duration: "04:04",
      youtubeId: "co6WMzDOh1o",
      thumbnail: "https://i.ytimg.com/vi/co6WMzDOh1o/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554674",
    },
    {
      name: "IStillHaven3...",
      artist: "U2",
      type: "song",
      duration: "04:36",
      youtubeId: "e3-5YC_oHjE",
      thumbnail: "https://i.ytimg.com/vi/e3-5YC_oHjE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787554675",
    },
    {
      name: "DancingInthe...",
      artist: "BruceSprings...",
      type: "song",
      duration: "03:59",
      youtubeId: "129kuDCQtHs",
      thumbnail: "https://i.ytimg.com/vi/129kuDCQtHs/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555190",
    },
    {
      name: "TheRiver",
      artist: "BruceSprings...",
      type: "song",
      duration: "07:04",
      youtubeId: "lc6F47Z6PI4",
      thumbnail: "https://i.ytimg.com/vi/lc6F47Z6PI4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555193",
    },
    {
      name: "BornintheUSA",
      artist: "BruceSprings...",
      type: "song",
      duration: "04:44",
      youtubeId: "EPhWR4d3FJQ",
      thumbnail: "https://i.ytimg.com/vi/EPhWR4d3FJQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555197",
    },
    {
      name: "StreetsofPhi...",
      artist: "BruceSprings...",
      type: "song",
      duration: "02:58",
      youtubeId: "4z2DtNW79sQ",
      thumbnail: "https://i.ytimg.com/vi/4z2DtNW79sQ/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555200",
    },
    {
      name: "My Hometown",
      artist: "Bruce Springsteen",
      type: "song",
      duration: "05:41",
      youtubeId: "KZ3BJYx43y0",
      thumbnail: "https://i.ytimg.com/vi/KZ3BJYx43y0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555203",
    },
  
    {
      name: "Part Time Love",
      artist: "Stevie Wonder",
      type: "song",
      duration: "07:34",
      youtubeId: "uzbRoG6XFlg",
      thumbnail: "https://i.ytimg.com/vi/uzbRoG6XFlg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555660",
    },
    {
      name: "IJustCalledT...",
      artist: "StevieWonder",
      type: "song",
      duration: "04:53",
      youtubeId: "XxoBaEQGMPo",
      thumbnail: "https://i.ytimg.com/vi/XxoBaEQGMPo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555663",
    },
    {
      name: "FaithftArian...",
      artist: "StevieWonder",
      type: "song",
      duration: "02:44",
      youtubeId: "hNMMN46uFCc",
      thumbnail: "https://i.ytimg.com/vi/hNMMN46uFCc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555668",
    },
    {
      name: "ampTheRevolu...",
      artist: "Prince",
      type: "song",
      duration: "03:45",
      youtubeId: "UG3VcCAlUgE",
      thumbnail: "https://i.ytimg.com/vi/UG3VcCAlUgE/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555990",
    },
    {
      name: "ampTheRevolu...",
      artist: "Prince",
      type: "song",
      duration: "03:56",
      youtubeId: "H9tEvfIsDyo",
      thumbnail: "https://i.ytimg.com/vi/H9tEvfIsDyo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555991",
    },
    {
      name: "TheMostBeaut...",
      artist: "Prince",
      type: "song",
      duration: "04:56",
      youtubeId: "FuXbKLiW1UI",
      thumbnail: "https://i.ytimg.com/vi/FuXbKLiW1UI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555992",
    },
    {
      name: "quotWhileMyG...",
      artist: "2021Remaster",
      type: "song",
      duration: "06:22",
      youtubeId: "dWRCooFKk3c",
      thumbnail: "https://i.ytimg.com/vi/dWRCooFKk3c/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555994",
    },
    {
      name: "ampTheNewPow...",
      artist: "Prince",
      type: "song",
      duration: "06:04",
      youtubeId: "rrbFQEcpJ3A",
      thumbnail: "https://i.ytimg.com/vi/rrbFQEcpJ3A/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787555996",
    },
    {
      name: "SmellsLikeTe...",
      artist: "Nirvana",
      type: "song",
      duration: "04:39",
      youtubeId: "hTWKbfoikeg",
      thumbnail: "https://i.ytimg.com/vi/hTWKbfoikeg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556344",
    },
    {
      name: "ComeAsYouAre",
      artist: "Nirvana",
      type: "song",
      duration: "03:45",
      youtubeId: "vabnZ9-ex7o",
      thumbnail: "https://i.ytimg.com/vi/vabnZ9-ex7o/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556345",
    },
    {
      name: "TheManWhoSol...",
      artist: "Nirvana",
      type: "song",
      duration: "03:38",
      youtubeId: "fregObNcHC8",
      thumbnail: "https://i.ytimg.com/vi/fregObNcHC8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556347",
    },
    {
      name: "Lithium",
      artist: "Nirvana",
      type: "song",
      duration: "04:16",
      youtubeId: "pkcJEvMcnEg",
      thumbnail: "https://i.ytimg.com/vi/pkcJEvMcnEg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556348",
    },
    {
      name: "HeartShapedB...",
      artist: "Nirvana",
      type: "song",
      duration: "04:43",
      youtubeId: "n6P0SitRwy8",
      thumbnail: "https://i.ytimg.com/vi/n6P0SitRwy8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556350",
    },
    {
      name: "Hurt",
      artist: "JohnnyCash",
      type: "song",
      duration: "03:49",
      youtubeId: "8AHCfZTRGiI",
      thumbnail: "https://i.ytimg.com/vi/8AHCfZTRGiI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556778",
    },
    {
      name: "IWalktheLine",
      artist: "JohnnyCash",
      type: "song",
      duration: "02:35",
      youtubeId: "J5126CibNsk",
      thumbnail: "https://i.ytimg.com/vi/J5126CibNsk/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556779",
    },
    {
      name: "God39sGonnaC...",
      artist: "JohnnyCash",
      type: "song",
      duration: "02:52",
      youtubeId: "eJlN9jdQFSc",
      thumbnail: "https://i.ytimg.com/vi/eJlN9jdQFSc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556781",
    },
    {
      name: "FolsomPrison...",
      artist: "JohnnyCash",
      type: "song",
      duration: "02:43",
      youtubeId: "AeZRYhLDLeU",
      thumbnail: "https://i.ytimg.com/vi/AeZRYhLDLeU/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556782",
    },
    {
      name: "RingOfFireCO...",
      artist: "JohnnyCash",
      type: "song",
      duration: "02:35",
      youtubeId: "1Osyw6Svv8U",
      thumbnail: "https://i.ytimg.com/vi/1Osyw6Svv8U/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787556785",
    },
    {
      name: "ISayALittleP...",
      artist: "ArethaFrankl...",
      type: "song",
      duration: "03:39",
      youtubeId: "TDyiREoBw0o",
      thumbnail: "https://i.ytimg.com/vi/TDyiREoBw0o/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787557107",
    },
    {
      name: "GreatestHits...",
      artist: "ArethaFrankl...",
      type: "song",
      duration: "01:09:11",
      youtubeId: "wNwUQJzPY20",
      thumbnail: "https://i.ytimg.com/vi/wNwUQJzPY20/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787557108",
    },
    {
      name: "Respect",
      artist: "ArethaFrankl...",
      type: "song",
      duration: "02:30",
      youtubeId: "6FOUqQt3Kg0",
      thumbnail: "https://i.ytimg.com/vi/6FOUqQt3Kg0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787557110",
    },
    {
      name: "EverChanging...",
      artist: "ArethaFrankl...",
      type: "song",
      duration: "04:32",
      youtubeId: "AM0MVuEmFGc",
      thumbnail: "https://i.ytimg.com/vi/AM0MVuEmFGc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787557111",
    },
    {
      name: "ISayaLittleP...",
      artist: "ArethaFrankl...",
      type: "song",
      duration: "03:37",
      youtubeId: "-8y0onSG3kg",
      thumbnail: "https://i.ytimg.com/vi/-8y0onSG3kg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787557113",
    },
    {
      name: "Kashmir",
      artist: "LedZeppelin",
      type: "song",
      duration: "09:07",
      youtubeId: "PD-MdiUm1_Y",
      thumbnail: "https://i.ytimg.com/vi/PD-MdiUm1_Y/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787561702",
    },
    {
      name: "I Say ALittle Pray for you.",
      artist: "Aretha Franklin.",
      type: "song",
      duration: "03:44",
      youtubeId: "7Ifw8JhDBvs",
      thumbnail: "https://i.ytimg.com/vi/7Ifw8JhDBvs/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566267",
    },
    {
      name: "Fly Me To TheMoon",
      artist: "Frank Sinatra",
      type: "song",
      duration: "02:28",
      youtubeId: "ZEcqHA7dbwM",
      thumbnail: "https://i.ytimg.com/vi/ZEcqHA7dbwM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566629",
    },
    {
      name: "My Way",
      artist: "Frank Sinatra",
      type: "song",
      duration: "04:37",
      youtubeId: "qQzdAsjWGPg",
      thumbnail: "https://i.ytimg.com/vi/qQzdAsjWGPg/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566631",
    },
    {
      name: "MyWay",
      artist: "FrankSinatra",
      type: "song",
      duration: "04:16",
      youtubeId: "w019MzRosmk",
      thumbnail: "https://i.ytimg.com/vi/w019MzRosmk/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566632",
    },
    {
      name: "39sLife",
      artist: "That",
      type: "song",
      duration: "03:08",
      youtubeId: "TnlPtaPxXfc",
      thumbnail: "https://i.ytimg.com/vi/TnlPtaPxXfc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566633",
    },
  
    {
      name: "Run th eWorld",
      artist: "Beyonce",
      type: "song",
      duration: "04:51",
      youtubeId: "VBmMU_iwe6U",
      thumbnail: "https://i.ytimg.com/vi/VBmMU_iwe6U/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566980",
    },
    {
      name: "Halo",
      artist: "Beyonce",
      type: "song",
      duration: "03:45",
      youtubeId: "bnVUHWCynig",
      thumbnail: "https://i.ytimg.com/vi/bnVUHWCynig/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566981",
    },
    {
      name: "LoveOnTop",
      artist: "Beyonc",
      type: "song",
      duration: "03:17",
      youtubeId: "Ob7vObnFUJc",
      thumbnail: "https://i.ytimg.com/vi/Ob7vObnFUJc/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566983",
    },
    {
      name: "IfIWereABoy",
      artist: "Beyonc",
      type: "song",
      duration: "05:06",
      youtubeId: "AWpsOqh8q0M",
      thumbnail: "https://i.ytimg.com/vi/AWpsOqh8q0M/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566984",
    },
    {
      name: "BREAKMYSOUL",
      artist: "Beyonc",
      type: "song",
      duration: "04:47",
      youtubeId: "yjki-9Pthh0",
      thumbnail: "https://i.ytimg.com/vi/yjki-9Pthh0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787566985",
    },
    {
      name: "ampTheWailer...",
      artist: "BobMarley",
      type: "song",
      duration: "04:01",
      youtubeId: "1ti2YCFgCoI",
      thumbnail: "https://i.ytimg.com/vi/1ti2YCFgCoI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567330",
    },
    {
      name: "ampTheWailer...",
      artist: "BobMarley",
      type: "song",
      duration: "03:13",
      youtubeId: "HNBCVM4KbUM",
      thumbnail: "https://i.ytimg.com/vi/HNBCVM4KbUM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567332",
    },
    {
      name: "IsThisLove",
      artist: "BobMarley",
      type: "song",
      duration: "03:54",
      youtubeId: "69RdQFDuYPI",
      thumbnail: "https://i.ytimg.com/vi/69RdQFDuYPI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567333",
    },
    {
      name: "OneLove",
      artist: "BobMarley",
      type: "song",
      duration: "02:46",
      youtubeId: "vdB-8eLEW8g",
      thumbnail: "https://i.ytimg.com/vi/vdB-8eLEW8g/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567335",
    },
    {
      name: "ampTheWailer...",
      artist: "BobMarley",
      type: "song",
      duration: "02:43",
      youtubeId: "uMUQMSXLlHM",
      thumbnail: "https://i.ytimg.com/vi/uMUQMSXLlHM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567336",
    },
    {
      name: "Dreams",
      artist: "FleetwoodMac",
      type: "song",
      duration: "04:14",
      youtubeId: "mrZRURcb1cM",
      thumbnail: "https://i.ytimg.com/vi/mrZRURcb1cM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567669",
    },
    {
      name: "Dreams",
      artist: "FleetwoodMac",
      type: "song",
      duration: "04:24",
      youtubeId: "Y3ywicffOj4",
      thumbnail: "https://i.ytimg.com/vi/Y3ywicffOj4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567670",
    },
    {
      name: "Everywhere",
      artist: "FleetwoodMac",
      type: "song",
      duration: "04:03",
      youtubeId: "YF1R0hc5Q2I",
      thumbnail: "https://i.ytimg.com/vi/YF1R0hc5Q2I/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567671",
    },
    {
      name: "LittleLies",
      artist: "FleetwoodMac",
      type: "song",
      duration: "03:39",
      youtubeId: "uCGD9dT12C0",
      thumbnail: "https://i.ytimg.com/vi/uCGD9dT12C0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567672",
    },
    {
      name: "FleetwoodMac...",
      artist: "GoYourOwnWay",
      type: "song",
      duration: "06:09",
      youtubeId: "p8Ojjn35kP8",
      thumbnail: "https://i.ytimg.com/vi/p8Ojjn35kP8/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787567673",
    },
    {
      name: "DCThunderstr...",
      artist: "AC",
      type: "song",
      duration: "04:53",
      youtubeId: "v2AC41dglnM",
      thumbnail: "https://i.ytimg.com/vi/v2AC41dglnM/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568117",
    },
    {
      name: "DCBackInBlac...",
      artist: "AC",
      type: "song",
      duration: "04:14",
      youtubeId: "pAgnJDJN4VA",
      thumbnail: "https://i.ytimg.com/vi/pAgnJDJN4VA/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568119",
    },
    {
      name: "DCHighwaytoH...",
      artist: "AC",
      type: "song",
      duration: "04:45",
      youtubeId: "gEPmA3USJdI",
      thumbnail: "https://i.ytimg.com/vi/gEPmA3USJdI/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568120",
    },
    {
      name: "DCHighwaytoH...",
      artist: "AC",
      type: "song",
      duration: "03:28",
      youtubeId: "l482T0yNkeo",
      thumbnail: "https://i.ytimg.com/vi/l482T0yNkeo/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568121",
    },
    {
      name: "DCThunderstr...",
      artist: "AC",
      type: "song",
      duration: "05:21",
      youtubeId: "n_GFN3a0yj0",
      thumbnail: "https://i.ytimg.com/vi/n_GFN3a0yj0/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568122",
    },
    {
      name: "quotIGetArou...",
      artist: "TheBeachBoys",
      type: "song",
      duration: "02:01",
      youtubeId: "ruKCw797JM4",
      thumbnail: "https://i.ytimg.com/vi/ruKCw797JM4/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568481",
    },
    {
      name: "Good Vibrations",
      artist: "TheBeachBoys",
      type: "song",
      duration: "03:35",
      youtubeId: "apBWI6xrbLY",
      thumbnail: "https://i.ytimg.com/vi/apBWI6xrbLY/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568486",
    },
    {
      name: "Kokomo",
      artist: "The Beach Boys",
      type: "song",
      duration: "03:33",
      youtubeId: "fJWmbLS2_ec",
      thumbnail: "https://i.ytimg.com/vi/fJWmbLS2_ec/mqdefault.jpg",
      addedBy: "artist",
      addedAt: "1705787568491",
    },
  ];