export const top200MusicArtistsBands = [
  "The Beatles",
  "Michael Jackson",
  "Elvis Presley",
  "Taylor Swift",
  "Beyoncé",
  "Kanye West",
  "Drake",
  "Ariana Grande",
  "The Rolling Stones",
  "Led Zeppelin",
  "Queen",
  "The Weeknd",
  "Ed Sheeran",
  "Rihanna",
  "Bruno Mars",
  "Justin Bieber",
  "Adele",
  "Eminem",
  "Madonna",
  "Pink Floyd",
  "David Bowie",
  "Prince",
  "Jay-Z",
  "Billie Eilish",
  "Lady Gaga",
  "Coldplay",
  "Kendrick Lamar",
  "Post Malone",
  "Fleetwood Mac",
  "Nirvana",
  "The Eagles",
  "Bruce Springsteen",
  "U2",
  "Bob Dylan",
  "The Who",
  "Whitney Houston",
  "The Beach Boys",
  "ABBA",
  "Frank Sinatra",
  "Metallica",
  "Maroon 5",
  "Sia",
  "Travis Scott",
  "Linkin Park",
  "Radiohead",
  "Dua Lipa",
  "Katy Perry",
  "Lil Wayne",
  "Cardi B",
  "Jimi Hendrix",
  "John Lennon",
  "Red Hot Chili Peppers",
  "The Doors",
  "Miley Cyrus",
  "Lana Del Rey",
  "Harry Styles",
  "The Police",
  "The Killers",
  "Oasis",
  "Rage Against The Machine",
  "Elton John",
  "Shawn Mendes",
  "Sam Smith",
  "Imagine Dragons",
  "Green Day",
  "Pink",
  "Doja Cat",
  "Lil Nas X",
  "Alicia Keys",
  "Tupac Shakur",
  "The Notorious B.I.G.",
  "Pearl Jam",
  "Aerosmith",
  "The Clash",
  "Guns N’ Roses",
  "Bob Marley",
  "Florence + The Machine",
  "Bon Jovi",
  "Blink-182",
  "Shakira",
  "The Black Keys",
  "The Strokes",
  "The Smashing Pumpkins",
  "Depeche Mode",
  "Foo Fighters",
  "Janet Jackson",
  "Kacey Musgraves",
  "Lil Baby",
  "J. Cole",
  "Chris Brown",
  "Usher",
  "Nicki Minaj",
  "XXXTentacion",
  "Bill Withers",
  "Tina Turner",
  "Stevie Wonder",
  "George Michael",
  "Phil Collins",
  "Simon & Garfunkel",
  "Kiss",
  "Panic! At The Disco",
  "Childish Gambino",
  "Nas",
  "2Pac",
  "Snoop Dogg",
  "Frank Ocean",
  "Megan Thee Stallion",
  "Tyler, The Creator",
  "Lil Uzi Vert",
  "Future",
  "Trippie Redd",
  "Halsey",
  "Zayn Malik",
  "Camila Cabello",
  "Demi Lovato",
  "Ellie Goulding",
  "Tove Lo",
  "Jessie J",
  "The Chainsmokers",
  "DJ Khaled",
  "Avicii",
  "Calvin Harris",
  "Tiesto",
  "Marshmello",
  "Martin Garrix",
  "Kygo",
  "Zedd",
  "Daft Punk",
  "Deadmau5",
  "David Guetta",
  "Justice",
  "The Chemical Brothers",
  "Disclosure",
  "Major Lazer",
  "Diplo",
  "Alan Walker",
  "Swedish House Mafia",
  "Steve Aoki",
  "The Prodigy",
  "Faithless",
  "Above & Beyond",
  "Paul Oakenfold",
  "Paul van Dyk",
  "Armin van Buuren",
  "Eric Prydz",
  "Fatboy Slim",
  "Moby",
  "Underworld",
  "Deftones",
  "Queens of the Stone Age",
  "Arctic Monkeys",
  "Mumford & Sons",
  "Vampire Weekend",
  "Tame Impala",
  "The White Stripes",
  "Jack White",
  "Kings of Leon",
  "The Lumineers",
  "Of Monsters and Men",
  "The 1975",
  "Bastille",
  "Twenty One Pilots",
  "The Neighbourhood",
  "Imagine Dragons",
  "Arcade Fire",
  "LCD Soundsystem",
  "Phoenix",
  "The National",
  "Beck",
  "The Flaming Lips",
  "Grimes",
  "Car Seat Headrest",
  "The War on Drugs",
  "Bon Iver",
  "Sufjan Stevens",
  "Father John Misty",
  "Mac DeMarco",
  "MGMT",
  "Foster The People",
  "Chvrches",
  "Purity Ring",
  "Crystal Castles",
  "Passion Pit",
  "Portugal. The Man",
  "The XX",
  "Lorde",
  "Vance Joy",
  "Shawn Mendes",
  "Troye Sivan",
  "Billie Joe Armstrong",
  "Stevie Nicks",
  "Diana Ross",
  "Barry White",
  "Marvin Gaye",
  "Aretha Franklin",
  "James Brown",
  "Ray Charles",
  "Smokey Robinson",
  "The Supremes",
  "Earth, Wind & Fire",
  "Al Green",
  "Curtis Mayfield",
  "Isaac Hayes",
  "Otis Redding",
  "The Temptations",
  "The Four Tops",
  "The Jackson 5",
  "The Commodores",
  "The Isley Brothers",
  "Sam Cooke",
  "Gladys Knight & The Pips",
  "The O’Jays",
  "Patti LaBelle",
];
